name: PR

on:
  pull_request:
    branches:
      - master
    types: ["synchronize", "opened"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: ferluisxd/create-npmrc@3
        with:
          org_name: paopaojr
          auth_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use yarn 2
        run: |
          echo '${{ secrets.YARNRC }}' > .yarnrc.yml
          yarn set version berry
      - name: Install dependencies
        run: yarn install
      - name: Check
        run: yarn dlx ts-node ./bin/check.ts
